[package]
name = "pulstar"
version = "0.1.0"
edition = "2024"

[dependencies]
temp_name_lib = {path = "../temp_name_lib"}
nalgebra = "0.33.2"
polars = { version = "0.49.1", features = ["lazy","parquet"]}
serde = "1.0"
toml = "0.9.2"